#!/bin/sh
set -eu
if [ "$#" != "2" ]
then
	echo "Usage: $0 filein fileout"
	exit 1
fi
SELF=$(realpath $0)
FILEIN=${1}
FILEOUT=${2}
PAYLOAD_LINE=$(awk '/^__TEMPLATE__/ { print NR + 1; exit 0; }' $SELF)
tail -n +$PAYLOAD_LINE $SELF > $FILEOUT
cat $FILEIN | od -v -A n --endian=big -t x1 | tr -d ' \n' >> $FILEOUT
chmod +x $FILEOUT
exit 0
__TEMPLATE__
#!/bin/sh
tail -n +7 $0 | while read -n 2 hex
do
	echo -ne "\x$hex" >> $1
done
exit 0
